@webapi_HostAddress = http://localhost:5242
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyNCIsIm5iZiI6MTc2NTA0MzEwMiwiZXhwIjoxNzY1MDQ2NzAyLCJpc3MiOiJ5b3VyLWFwcCIsImF1ZCI6InlvdXItY2xpZW50In0.h_O4sOUf99y8r9PnsJJiDAxnnYo0ICVGY-VlHViay_U
POST {{webapi_HostAddress}}/api/game/login
Content-Type: application/json

{
    "userId": "user5",
    "password": "hello"
}

POST {{webapi_HostAddress}}/api/game/register
Content-Type: application/json

{
    "userId": "user5",
    "password": "hello"
}

GET {{webapi_HostAddress}}/api/game/user
Authorization: Bearer {{access_token}}
Content-Type: application/json


// item inventory 
GET {{webapi_HostAddress}}/api/game/items
Authorization: Bearer {{access_token}}
Accept: application/json

GET {{webapi_HostAddress}}/api/game/item-random
Accept: application/json

POST {{webapi_HostAddress}}/api/game/item-add
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "itemId": "food001"
}

// leaderboard
GET {{webapi_HostAddress}}/api/game/leaderboard

POST {{webapi_HostAddress}}/api/game/score
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "score": 1091
}

###
