@webapi_HostAddress = http://localhost:5242
@access_token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMSIsIm5iZiI6MTc2NTM1NTk3NCwiZXhwIjoxNzY1MzU5NTc0LCJpc3MiOiJ5b3VyLWFwcCIsImF1ZCI6InlvdXItY2xpZW50In0.Ue2lL2qhrHlQvX4iBBmjpGgknAG9ecw6CMKryDYrESw
POST {{webapi_HostAddress}}/api/game/login
Content-Type: application/json

{
    "userId": "user1",
    "password": "hello"
}

POST {{webapi_HostAddress}}/api/game/register
Content-Type: application/json

{
    "userId": "user5",
    "password": "hello"
}

GET {{webapi_HostAddress}}/api/game/user
Authorization: Bearer {{access_token}}
Content-Type: application/json


// item inventory 
GET {{webapi_HostAddress}}/api/game/items
Authorization: Bearer {{access_token}}
Accept: application/json

POST {{webapi_HostAddress}}/api/game/item-add
Authorization: Bearer {{access_token}}

// leaderboard
GET {{webapi_HostAddress}}/api/game/leaderboard

POST {{webapi_HostAddress}}/api/game/score
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "score": 250
}

###
